/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCanvas: typeof import('./src/components/AppCanvas/AppCanvas.vue')['default']
    AppCanvasInspectBox: typeof import('./src/components/AppCanvas/AppCanvasInspectBox.vue')['default']
    AppPanel: typeof import('./src/components/AppPanel.vue')['default']
    AppSettingsBoolean: typeof import('./src/components/AppSettingsForm/fields/boolean/AppSettingsBoolean.vue')['default']
    AppSettingsForm: typeof import('./src/components/AppSettingsForm/AppSettingsForm.vue')['default']
    AppSettingsNumberField: typeof import('./src/components/AppSettingsForm/fields/number/AppSettingsNumberField.vue')['default']
    AppSettingsSelect: typeof import('./src/components/AppSettingsForm/fields/select/AppSettingsSelect.vue')['default']
    AppSettingsTextField: typeof import('./src/components/AppSettingsForm/fields/text/AppSettingsTextField.vue')['default']
    AppView: typeof import('./src/components/AppView.vue')['default']
    AppWindow: typeof import('./src/components/AppWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiBtn: typeof import('./../ui/src/components/UiBtn/UiBtn.vue')['default']
    UiCheckbox: typeof import('./../ui/src/components/UiCheckbox/UiCheckbox.vue')['default']
    UiForm: typeof import('./../ui/src/components/UiForm/UiForm.vue')['default']
    UiIcon: typeof import('./../ui/src/components/UiIcon/UiIcon.vue')['default']
    UiInput: typeof import('./../ui/src/components/UiInput/UiInput.vue')['default']
    UiOverlayMenu: typeof import('./../ui/src/components/UiOverlayMenu/UiOverlayMenu.vue')['default']
    UiPopup: typeof import('./../ui/src/components/UiOverlayMenu/UiPopup.vue')['default']
    UiSelect: typeof import('./../ui/src/components/UiSelect/UiSelect.vue')['default']
    UiTextField: typeof import('./../ui/src/components/UiTextField/UiTextField.vue')['default']
  }
}
