export * as commands from './commands'
export * as contextMenu from './contextMenu'
export * as files from './files'
export * as shortcuts from './shortcuts'
export * as toolbar from './toolbar'
export * as views from './views'