/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCanvas: typeof import('./src/components/AppCanvas/AppCanvas.vue')['default']
    AppCanvasInspectBox: typeof import('./src/components/AppCanvas/AppCanvasInspectBox.vue')['default']
    AppCommandPalette: typeof import('./src/components/AppCommandPalette.vue')['default']
    AppMenubar: typeof import('./src/components/AppMenuBar/AppMenubar.vue')['default']
    AppMenuCheckGroupItem: typeof import('./src/components/AppMenuBar/AppMenuCheckGroupItem.vue')['default']
    AppMenuTree: typeof import('./src/components/AppMenuBar/AppMenuTree.vue')['default']
    AppMenuTreeItem: typeof import('./src/components/AppMenuBar/AppMenuTreeItem.vue')['default']
    AppPanel: typeof import('./src/components/AppPanel.vue')['default']
    AppPrompt: typeof import('./src/components/AppPrompt.vue')['default']
    AppSettingsBoolean: typeof import('./src/components/AppSettingsForm/fields/boolean/AppSettingsBoolean.vue')['default']
    AppSettingsForm: typeof import('./src/components/AppSettingsForm/AppSettingsForm.vue')['default']
    AppSettingsNumberField: typeof import('./src/components/AppSettingsForm/fields/number/AppSettingsNumberField.vue')['default']
    AppSettingsSelect: typeof import('./src/components/AppSettingsForm/fields/select/AppSettingsSelect.vue')['default']
    AppSettingsTextField: typeof import('./src/components/AppSettingsForm/fields/text/AppSettingsTextField.vue')['default']
    AppWebview: typeof import('./src/components/AppWebview/AppWebview.vue')['default']
    AppWebWindow: typeof import('./src/components/AppWindow/AppWebWindow.vue')['default']
    AppWidget: typeof import('./src/components/AppWidget/AppWidget.vue')['default']
    AppWindow: typeof import('./src/components/AppWindow/AppWindow.vue')['default']
    AppWindowManager: typeof import('./src/components/AppWindow/AppWindowManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiBtn: typeof import('./../ui/src/components/UiBtn/UiBtn.vue')['default']
    UiCheckbox: typeof import('./../ui/src/components/UiCheckbox/UiCheckbox.vue')['default']
    UiForm: typeof import('./../ui/src/components/UiForm/UiForm.vue')['default']
    UiIcon: typeof import('./../ui/src/components/UiIcon/UiIcon.vue')['default']
    UiInput: typeof import('./../ui/src/components/UiInput/UiInput.vue')['default']
    UiKbd: typeof import('./../ui/src/components/UiKbd/UiKbd.vue')['default']
    UiMenu: typeof import('./../ui/src/components/UiMenu/UiMenu.vue')['default']
    UiMenuBar: typeof import('./../ui/src/components/UiMenuBar/UiMenuBar.vue')['default']
    UiMenuGroup: typeof import('./../ui/src/components/UiMenu/UiMenuGroup.vue')['default']
    UiMenuItem: typeof import('./../ui/src/components/UiMenu/UiMenuItem.vue')['default']
    UiMenuItemSeparator: typeof import('./../ui/src/components/UiMenu/UiMenuItemSeparator.vue')['default']
    UiOverlayMenu: typeof import('./../ui/src/components/UiOverlayMenu/UiOverlayMenu.vue')['default']
    UiPopup: typeof import('./../ui/src/components/UiOverlayMenu/UiPopup.vue')['default']
    UiRadio: typeof import('./../ui/src/components/UiRadio/UiRadio.vue')['default']
    UiSelect: typeof import('./../ui/src/components/UiSelect/UiSelect.vue')['default']
    UiTextField: typeof import('./../ui/src/components/UiTextField/UiTextField.vue')['default']
    UiWindow: typeof import('./../ui/src/components/UiWindow/UiWindow.vue')['default']
  }
}
