[package]
name = "lenz_core"
version = "0.1.0"
edition = "2021"
authors = ["Salomão Neto <contato@sallon.dev>"]

[dependencies]
bytes = {workspace =true }
mime_guess = {workspace =true}
serde = { workspace=true }
serde_json = {workspace = true}
tokio = {workspace = true}
dirs = "5.0.1"