/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiBtn: typeof import('./src/components/UiBtn/UiBtn.vue')['default']
    UiCheckbox: typeof import('./src/components/UiCheckbox/UiCheckbox.vue')['default']
    UiForm: typeof import('./src/components/UiForm/UiForm.vue')['default']
    UiIcon: typeof import('./src/components/UiIcon/UiIcon.vue')['default']
    UiInput: typeof import('./src/components/UiInput/UiInput.vue')['default']
    UiOverlayMenu: typeof import('./src/components/UiOverlayMenu/UiOverlayMenu.vue')['default']
    UiPopup: typeof import('./src/components/UiOverlayMenu/UiPopup.vue')['default']
    UiSelect: typeof import('./src/components/UiSelect/UiSelect.vue')['default']
    UiTextField: typeof import('./src/components/UiTextField/UiTextField.vue')['default']
  }
}
