name: Deploy Website
description: Deploys the website to GitHub Pages when the build is successful.
on:
    workflow_run:
        workflows: ["Build and Release"]
        types:
            - completed
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Install Flatpak
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08 org.freedesktop.Sdk.Extension.rust-stable//24.08 org.freedesktop.Sdk.Extension.node22//24.08
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up PNPM
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build docs
      run: pnpm build:docs

    - name: Build Flatpak repo
      run: |
        pnpm flatpak:build
        pnpm flatpak:bundle
        cp -r repo docs/flatpak

    - name: "Create FlatpakRef"
      run: |
        cat <<EOF > docs/lenz.flatpakref
        [Flatpak Ref]
        Title=Lenz Designer
        Name=dev.sallon.lenz
        Branch=master
        Runtime=org.freedesktop.Platform//24.08
        Url=https://sallon.dev/lenz/flatpak
        Arch=x86_64
        Comment=Um editor de páginas HTML para todos
        Icon=dev.sallon.lenz
        EOF

    - name: Upload docs to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4